// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: waku_message.proto

package protocol

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type WakuMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload      []byte  `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	ContentTopic uint32  `protobuf:"varint,2,opt,name=contentTopic,proto3" json:"contentTopic,omitempty"`
	Version      uint32  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Proof        []byte  `protobuf:"bytes,4,opt,name=proof,proto3" json:"proof,omitempty"`
	Timestamp    float64 `protobuf:"fixed64,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *WakuMessage) Reset() {
	*x = WakuMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_waku_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WakuMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WakuMessage) ProtoMessage() {}

func (x *WakuMessage) ProtoReflect() protoreflect.Message {
	mi := &file_waku_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WakuMessage.ProtoReflect.Descriptor instead.
func (*WakuMessage) Descriptor() ([]byte, []int) {
	return file_waku_message_proto_rawDescGZIP(), []int{0}
}

func (x *WakuMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WakuMessage) GetContentTopic() uint32 {
	if x != nil {
		return x.ContentTopic
	}
	return 0
}

func (x *WakuMessage) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *WakuMessage) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *WakuMessage) GetTimestamp() float64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_waku_message_proto protoreflect.FileDescriptor

var file_waku_message_proto_rawDesc = []byte{
	0x0a, 0x12, 0x77, 0x61, 0x6b, 0x75, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x22, 0x99,
	0x01, 0x0a, 0x0b, 0x57, 0x61, 0x6b, 0x75, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x18, 0x0a, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x12, 0x1c, 0x0a, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_waku_message_proto_rawDescOnce sync.Once
	file_waku_message_proto_rawDescData = file_waku_message_proto_rawDesc
)

func file_waku_message_proto_rawDescGZIP() []byte {
	file_waku_message_proto_rawDescOnce.Do(func() {
		file_waku_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_waku_message_proto_rawDescData)
	})
	return file_waku_message_proto_rawDescData
}

var file_waku_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_waku_message_proto_goTypes = []interface{}{
	(*WakuMessage)(nil), // 0: protocol.WakuMessage
}
var file_waku_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_waku_message_proto_init() }
func file_waku_message_proto_init() {
	if File_waku_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_waku_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WakuMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_waku_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_waku_message_proto_goTypes,
		DependencyIndexes: file_waku_message_proto_depIdxs,
		MessageInfos:      file_waku_message_proto_msgTypes,
	}.Build()
	File_waku_message_proto = out.File
	file_waku_message_proto_rawDesc = nil
	file_waku_message_proto_goTypes = nil
	file_waku_message_proto_depIdxs = nil
}
